GET http://localhost:3012/api/movies

###

GET http://localhost:3012/api/movies/1

###

POST http://localhost:3012/api/movies
Content-Type: application/json

{
      "id": 9,
      "title": "blabla",
      "released": "2000",
      "duration": "1h",
      "imdb": "7"
}

###

PUT http://localhost:3012/api/movies/8
Content-Type: application/json

{
      "id": 8,
      "title": "blablablaa",
      "released": "2000",
      "duration": "1h",
      "imdb": "7"
}

###

DELETE http://localhost:3012/api/movies/9
Content-Type: application/json

###

PATCH http://localhost:3012/api/movies/1
Content-Type: application/json

{
      "title": "The Hangover"
}